# -------------------------------------------------------------------------------------------------
# WebSocket configuration for the communication between plugin components.
#
# For proxied servers, this informations are not used.
# Just give them a random valid value.
#
# Host: The host address to bind the WebSocket server to.
# Port: The port number on which the WebSocket server will listen for connections.
# Password: The password required to authenticate WebSocket connections.
# -------------------------------------------------------------------------------------------------
WebSocket:
  Host: ""
  Port: null
  Password: ""

# -------------------------------------------------------------------------------------------------
# A list of parts of the plugin that will print log messages. Useful to see what the plugin does
# and solve issues.
#
# Do not fear enabling this otherwise you will miss out and then waste time reading our Wiki and
# opening tickets where things could easily be explained simply by reading the console.
#
# Available: websocket
# -------------------------------------------------------------------------------------------------
Debug: []
